- set:
    EthBtcSwap: "0x5d756b5073bf9cd72e6f641b6f39f8b44ff5b944"


# 1 ether, 0.26BTC
-
  transact:
    CreateTicket:
      gas: 500000
      to: $EthBtcSwap
      fun_name: createTicket
      sig: iii
      value: 1000000000000000000
      data:
        - 0x956bfc5575c0a7134c7effef268e51d887ba7015
        - 1000000000000000000
        - 38461538461
      wait: True

# deposit is 1 ether / 20
-
  transact:
    ReserveTicket:
      gas: 500000
      to: $EthBtcSwap
      fun_name: reserveTicket
      sig: ii
      value: 50000000000000000
      data:
        - $CreateTicket
        - 0x141e4ea2fa3c9bf9984d03ff081d21555f8ccc7a528326cea96221ca6d476566
      wait: True

-
  call:
    ClaimTicket:
      gas: 3000000
      to: $EthBtcSwap
      fun_name: claimTicket
      sig: isiiai
      value: 50000000000000000
      data:
        - $CreateTicket
        - "01000000014dff4050dcee16672e48d755c6dd25d324492b5ea306f85a3ab23b4df26e16e9000000008c493046022100cb6dc911ef0bae0ab0e6265a45f25e081fc7ea4975517c9f848f82bc2b80a909022100e30fb6bb4fb64f414c351ed3abaed7491b8f0b1b9bcd75286036df8bfabc3ea5014104b70574006425b61867d2cbb8de7c26095fbc00ba4041b061cf75b85699cb2b449c6758741f640adffa356406632610efb267cb1efa0442c207059dd7fd652eeaffffffff020049d971020000001976a91461cf5af7bb84348df3fd695672e53c7d5b3f3db988ac30601c0c060000001976a914fd4ed114ef85d350d6d40ed3f6dc23743f8f99c488ac00000000"
        - 0x7301b595279ece985f0c415e420e425451fcf7f684fcce087ba14d10ffec1121
        - 1
        - [0xb39fa6c39b99683ac8f456721b270786c627ecb246700888315991877024b983, 0x9ceb25811bcf8338941f173ce5965cba608306543afd08c446e0351d2e82ca50, 0xa3355d8406df7f35feae4db17fbb7902765dea3a554e30c09f5c90735b99daa9, 0x711c5efab5d310b49be61c039e6c611d84556645f724c8f9b7a4193e0ae1b87e, 0x970737453b169e0508208fb55e20a83794905dfa655cddfa6572bdbe1c3cfcb7, 0x6539cd92a2947b140b646e899d437ed604089ca58b02f9995bf2e66957521bd4, 0x9b282ac2bcf2656c2a968b69b807c02e3d71252477ff9cedd3f8a16a4e30dd5a, 0xc6dd553f393d1b7694ae168e8f5efeba8db4c3b000c2d9bf5205dd19f96c08a8]
        - 0x000000000000000082ccf8f1557c5d40b21edabb18d2d691cfbf87118bac7254
      wait: True
